# Generated by Django 4.1 on 2022-08-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(default='Other', max_length=255)),
                ('location', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('dob', models.DateField(null=True)),
                ('phone', models.TextField(null=True)),
                ('cell', models.TextField(null=True)),
                ('id', models.TextField(null=True)),
                ('nationality', models.CharField(max_length=255, null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('registered', models.DateField(null=True)),
                ('username', models.TextField(null=True)),
                ('uuid', models.CharField(default=0, max_length=255, primary_key=True, serialize=False)),
                ('city', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('postcode', models.TextField(null=True)),
            ],
        ),
    ]
